version: '3.9'

networks:
  appnet:
    driver: bridge

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: app1
    networks:
      - appnet

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: app2
    networks:
      - appnet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: appnginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
    networks:
      - appnet
